
server:
  port: 8081
  servlet:
    context-path: /ccs

system:
    scan_period: 3
    ftp:
      relativePath: /home/ftpccs/task
      username: ftpccs
      password: root
      server: 192.168.11.173
      port: 21
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.14.215:3306/thinkit?&characterEncoding=UTF8
      username: root
      password: 123456
      dbcp2:
           min-idle: 5                                           # 数据库连接池的最小维持连接数
           initial-size: 5                                       # 初始化连接数
           max-total: 5                                          # 最大连接数
           max-wait-millis: 200
    dispatch:
      shandong: true
      hebei: true
      beijing: true

    voice_engine_url: 123456789
    xml_engine_url: 1234567890

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.telecom.ccs.model    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml                       # mapper映射文件




# Elasticsearch
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
elasticsearch:
        ip: 192.168.11.173
        port: 9300
        pool: 5
        cluster:
              name: myapp-elasticsearch64on173



spring:
      redis:
        host: 192.168.11.173
        port: 6379
        database: 5
        jedis:
          pool:
              max-active: 8
              max-idle: 8
              min-idle: 0
              max-wait: -1ms                              # 等待连接获取的最大超时时间
          timeout: 5000


