
server:
  port: 8081
  servlet:
    context-path: /ccs

system:
    ftp:
      relativePath: /home/ftpuser/task
      username: ftpuser
      password: 12345678
      server: 172.16.153.149
      port: 21

    dispatch:
      shandong: true
      hebei: false
      beijing: false

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.telecom.ccs.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.153.149:3306/dx_ngquality
        username: root
        password: dxQuality@thinkit123
        dbcp2:
             min-idle: 5                                           # 数据库连接池的最小维持连接数
             initial-size: 5                                       # 初始化连接数
             max-total: 5                                          # 最大连接数
             max-wait-millis: 200


# Elasticsearch
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
elasticsearch:
        ip: 172.16.153.149
        port: 9300
        pool: 5
        cluster:
              name: elasticsearch



spring:
      redis:
        host: 172.16.153.149
        port: 6379
        database: 0
        jedis:
          pool:
              max-active: 8
              max-idle: 8
              min-idle: 0
              max-wait: -1ms                              # 等待连接获取的最大超时时间
          timeout: 5000


